services:
  dessert_fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dessert_fe
    image: dessert_fe
    restart: always
    expose:
      - '3000'
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: dessert_fe_nginx
    restart: always
    ports:
      - '8855:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dessert_fe
