name: Check code

on:
  pull_request:
    branches: ['develop', 'master']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: Set Yarn Version & install
        run: |
          corepack enable && corepack prepare yarn@stable
          yarn install --immutable

      - name: Run vitest
        run: yarn test:no-watch

      - name: build test
        run: yarn build
