name: Check code

on:
  pull_request:
    branches: ['develop', 'master']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install packages
        run: |
          corepack enable && corepack prepare yarn@4.1.1
          yarn install --immutable

      - name: Check lint
        run: yarn run lint-diff

      - name: Run vitest
        run: yarn test:no-watch
